version: '3.8'

services:
  postgres:
    image: postgres
    container_name: post-api-postgres
    environment:
      - POSTGRES_PASSWORD=password123
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - post-api-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      retries: 5
      timeout: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: post-api-app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - post-api-network
    ports:
      - '8080:8080'
    expose:
      - 8080
    env_file:
      - .env

networks:
  post-api-network:
    driver: bridge